### ISSUE TITLE
NullPointerException when incrementing versionCode

### ISSUE THREAD

**Issue by avrahamshukron** [moallemi/gradle-advanced-build-version#16]
The versionPropsFile property of the VersionCodeOptions class is only initialized in the getVersionCode getter.

But the plugin tries to access this property before it calls to getVersionCode, and thus receiving a null file reference, which crashes when it check whether it canRead().

**Comment by valllllll2000** [comment]
Hey, I have found the same problem, is there a workaround? Thanks

**Comment by valllllll2000** [comment]
actually I had forgotten to add versionCode advancedVersioning.versionCode to defaultConfig, once I have added that, the error was gone
