### ISSUE TITLE
AUTO_INCREMENT_ONE_STEP increments by 2

### ISSUE THREAD

**Issue by RobertAndale** [moallemi/gradle-advanced-build-version#18]
Hi,

I want to use your plugin, but when I test it unfortunately it increments version code by 2 (instead of 1)
For exemple, the version.properties contains AI_VERSION_CODE=3
In my build.gradle, I've specified  :
nameFormat 'MyApp-v${versionName}-rev${versionCode}-${buildType}'

When AI_VERSION_CODE=3 it generates following apks :
MyApp-v1.0-rev4-debug.apk
MyApp-v1.0-rev4-qualif.apk

Why not. But when it increments, the new version.propertiens contains AI_VERSION_CODE=5 (instead of 4). And then my next releases are :
MyApp-v1.0-rev6-debug.apk
MyApp-v1.0-rev6-qualif.apk

Could you fix this ?

**Comment by moallemi** [comment]
You should use `dependsOnTasks 'TASK_NAME'` in your `build.gradle` file and change TASK_NAME with the task you want to increase the version code. see https://github.com/moallemi/gradle-advanced-build-version#version-code-configuration for more info

**Comment by RobertAndale** [comment]
That's what I already do : 
codeOptions {
        versionCodeType org.moallemi.gradle.internal.VersionCodeType.AUTO_INCREMENT_ONE_STEP
        dependsOnTasks 'qualif'
    }

An that's not the purpose of the issue. The problem is that versionCode increases by 2. To be clearer, each time I buid a qualif apk (which is the task I want to increase the version code by 1), AI_VERSION_CODE increases by 2 ... (AI_VERSION_CODE contains 1, then 3, then 5, then 7 etc ....)
Please double check, and fix it.

**Comment by RobertAndale** [comment]
OK, I've found out what I was doing wrong. My task name was incorrect, because there was two tasks running containing "qualif". When I use 
dependsOnTasks "assembleQualif" 
it works fine. You can close the issue, then sorry, it was my mistake.
