### ISSUE TITLE
Code version mismatching 

### ISSUE THREAD

**Issue by KChernenko** [moallemi/gradle-advanced-build-version#24]
Hi! I'm using the following snippet:

```
advancedVersioning {
        nameOptions {
            versionMajor 1
            versionMinor 3
            versionPatch 6
            versionBuild versionCode
        }
        codeOptions {
            versionCodeType VersionCodeType.AUTO_INCREMENT_ONE_STEP
            dependsOnTasks 'debug', 'release', 'assemble'
        }

        outputOptions {
            renameOutput true
            nameFormat '${appName}-${buildType}-${versionName}'
        }
    }

    def appVersionName = advancedVersioning.versionName
    def appVersionCode = advancedVersioning.versionCode

   defaultConfig {
        ..........................
        versionName appVersionName
        versionCode appVersionCode
        multiDexEnabled true
    }
```

And I'm getting strange things. For example:
In `version.properties` the `AI_VERSION_CODE=43`
In `outputs -> apk` folder, apk's name: `app-debug-1.3.6.42.dev.apk`
Android Studio shows an error while installing apk:
`The APK file C:\apppath\app\build\outputs\apk\app-debug-1.3.6.37.dev.apk does not exist on disk.
Error while Installing APK`

**Comment by CeccoCQ** [comment]
Same issue for me.

**Comment by caman9119** [comment]
Nearly the exact same gradle file, I have the same issue.

**Comment by teodorshah** [comment]
Same issue. Something seems to be out of sync...

**Comment by minlite** [comment]
Same issue. Something seems to be out of sync...

**Comment by gonzalonm** [comment]
Same issue here. One **possible workaround** is add `android.enableBuildCache=false` on your _gradle.properties_ file. This property increment the time building but this issue is not reproducible (at least for me)
