### ISSUE TITLE
outputOptions -> renameOutput is broken with com.android.tools.build:gradle:2.2.0-alpha5

### ISSUE THREAD

**Issue by systembugtj** [moallemi/gradle-advanced-build-version#25]
Create a android app with Android studio 2.2 Preview 5.

It will use 2.2.0-alpha5.

And set outputOptions to renameOutput true

run assembleDebug

Didn't generate a rename apk.

**Comment by deviant-studio** [comment]
i can confirm that only unaligned apk is generated.
gradle plugin 2.2 (release)

**Comment by Vouskopes** [comment]
same problem apk has sufix -unaligned, but according to zipalign -c -v is aligned

**Comment by systembugtj** [comment]
2.2.2 android gradle plugins still has the issue

**Comment by moallemi** [comment]
@systembugtj As described in documentation, the rename task is only triggered in `release` builds:

```
dependsOnTasks 'release' // defaultValue
```
you can change it to any task:
```
dependsOnTasks 'debug', 'release', 'assemble'
```
