### ISSUE TITLE
The Android Gradle plugin 3.0.0-alpha3 is not supported

### ISSUE THREAD

**Issue by drakeet** [moallemi/gradle-advanced-build-version#28]
Hello, I am using the library in my project [TimeMachine](https://github.com/drakeet/TimeMachine), and when using `classpath 'com.android.tools.build:gradle:3.0.0-alpha3'` with the library, it built failed: 

```
Error:Cause: gradle-advanced-build-version says: The Android Gradle plugin 3.0.0-alpha3 is not supported.
```

Hope your help, thank you very much!

**Comment by ZuSe** [comment]
I would also like to see support for android gradle 3 >

**Comment by mkzaker** [comment]
**The Android Gradle plugin 3.0.0-beta4 is not supported.**
+1

**Comment by re3lex** [comment]
The Android Gradle plugin 3.0.0-beta4 is not supported.
+1

**Comment by drakeet** [comment]
Seems to be here to do the restrictions:

https://github.com/moallemi/gradle-advanced-build-version/blob/a2cbd62d62442102f1f5e321c96142de53e055bb/src/main/groovy/org/moallemi/gradle/AdvancedBuildVersionPlugin.groovy#L47

May I ask when to update support?

**Comment by moallemi** [comment]
I am waiting for latest stable gradle 3.0

**Comment by moallemi** [comment]
@drakeet @re3lex @mkzaker @ZuSe 
Would you please check the latest version `(1.6.0)` now?

**Comment by drakeet** [comment]
@moallemi 
It works fine with android gradle plugin `v3.0.0-beta7`. Thank you very much!

**Comment by re3lex** [comment]
Cool, thanks!

**Comment by mkzaker** [comment]
@moallemi 
It works fine with android gradle plugin v3.0.0-beta7
thanks!

**Comment by kulomady** [comment]
I tried with v3.0.0-rc2 got error : Error:No signature of method: java.util.ArrayList.all() is applicable for argument types: (org.moallemi.gradle.internal.FileOutputOptions$_generateOutputName_closure1) values: [org.moallemi.gradle.internal.FileOutputOptions$_generateOutputName_closure1@4367ee65]
Possible solutions: any(), tail(), tail(), last(), last(), add(java.lang.Object)
