### ISSUE TITLE
versionCode property doesn't work. 

### ISSUE THREAD

**Issue by Shellder** [moallemi/gradle-advanced-build-version#4]
Hi, I have a problem with versionCode property, when I add this property in build.gradle, after Sync get error:

Error:(17, 0) Could not read version.properties file in path "@PATH TO PROJECT HERE@\app\version.properties" 
Please create this file and add it to your VCS (git, svn, ...).

P.S. versionName property works

**Comment by moallemi** [comment]
Hi,
As the error describes you should create `version.properties` file manually. is this file already in the given path?

**Comment by Shellder** [comment]
I created a file manually and it started to work, thank you!
