### ISSUE TITLE
Unable to Build for gradle version 4.0.0

### ISSUE THREAD

**Issue by tonmoyray** [moallemi/gradle-advanced-build-version#45]
buildscript {
    ext.kotlin_version = "1.3.72"
    ext.nav_version = "2.3.0-beta01"
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
        classpath 'org.moallemi.gradle.advanced-build-version:gradle-plugin:1.6.0'
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

![image](https://user-images.githubusercontent.com/24776062/87669068-20a29c80-c78f-11ea-8085-9b54282884bb.png)

**Comment by moallemi** [comment]
Please use the [latest version ](https://github.com/moallemi/gradle-advanced-build-version/releases/latest) `1.7.1`
