### ISSUE TITLE
Stoped rename apk after gradle update

### ISSUE THREAD

**Issue by ggface** [moallemi/gradle-advanced-build-version#49]
I have updated gradle to 

> distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

and 

> classpath 'com.android.tools.build:gradle:4.1.0'

**Comment by moallemi** [comment]
Android Gradle Plugin 4.1.0 [drops support](https://developer.android.com/studio/known-issues#variant_output) for renaming apk.  You have to add `advancedVersioning.renameOutputApk()` after android configuration. The order is important:

```groovy
advancedVersioning {
  outputOptions {
    renameOutput true
  }
}
android {
  ...
}
advancedVersioning.renameOutputApk()
```

**Comment by ggface** [comment]
advancedVersioning.renameOutputApk() resolved my problem, thx
