### ISSUE TITLE
Failed to apply plugin [id 'me.moallemi.advanced-build-version']    > gradle-advanced-build-version only works with android application modules

### ISSUE THREAD

**Issue by zwirne** [moallemi/gradle-advanced-build-version#53]
Hey,

I upgradted Android Studio and now I'm getting the following error:

A problem occurred evaluating root project 'xxx'.
> Failed to apply plugin [id 'me.moallemi.advanced-build-version']
   > gradle-advanced-build-version only works with android application modules

I can't find anything related on the web. Do you got any advice?

thx
michael

**Comment by moallemi** [comment]
HI,

Did you upgrade the gradle-advanced-build-version to latest version` 1.7.3`?

What AGP plug-in are are you using in your project?

**Comment by zwirne** [comment]
Hi,

thanks for your quick reply!

I didn't upgrade to 1.7.3 at first, overlooked that.
After the update everything works fine.

Sorry for being blind.
Keep up the good work and thanks for your plugin!!!!

**Comment by kaviyarasu16** [comment]
I'm getting the same error. after upgraded it to 1.7.3
