### ISSUE TITLE
Update README to refer to pulling this from Maven Central instead of JCenter (which is due to sunset on 1st May 2021)

### ISSUE THREAD

**Issue by oliverlockwood** [moallemi/gradle-advanced-build-version#54]
See https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I'd like to keep using this project after 1st May 2021... and unless this is fixed I won't be able to!

**Comment by moallemi** [comment]
Hi Oliver,

This library is also [available on maven](https://search.maven.org/artifact/me.moallemi.gradle/advanced-build-version) from the first day. so do not worry. 

I have to update the README file.

Thanks

**Comment by oliverlockwood** [comment]
@moallemi I've updated the title of this ticket accordingly 😃  Thanks for easing my concern!

**Comment by moallemi** [comment]
Finally Done 😄
