### ISSUE TITLE
Gradle 7.0 support

### ISSUE THREAD

**Issue by edgar-zigis** [moallemi/gradle-advanced-build-version#56]
Hello,

we are already experimenting with Jetpack Compose and we are using this amazing plugin for our app versioning.
Unfortunately it is not supported by Gradle 7.0 and we get the following exception:

`org.gradle.api.GradleException: gradle-advanced-build-version does not support Android Gradle plugin 7.0.0-alpha14`

Are there any plans to add support for this plugin?

**Comment by moallemi** [comment]
@edgar-zigis Now you can use version `1.7.4` which supports AGP 7.0. 
Do not forget about using `mavenCentral `in your repositories. `jcenter` in not supported anymore

**Comment by edgar-zigis** [comment]
@moallemi thank you, awesome! 👍
