### ISSUE TITLE
Does not work with Gradle 7.x

### ISSUE THREAD

**Issue by oliverlockwood** [moallemi/gradle-advanced-build-version#59]
I see the following error:
```
> Could not resolve all artifacts for configuration ':app:classpath'.
   > Could not find com.android.tools.build:gradle:3.0.0.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :app > me.moallemi.gradle:advanced-build-version:1.7.3
```

I can see that there's been [a commit](https://github.com/moallemi/gradle-advanced-build-version/commit/bf29e349905cc2f8ed9aac8df9fd9963616466fd) in support of Gradle 7.x, but there's been no releases yet.

@moallemi any chance of you publishing a release so that we can work with Gradle 7.x, please?  Many thanks.

**Comment by moallemi** [comment]
@oliverlockwood You can use v1.7.4 which is compatible with AGP 7.x

**Comment by oliverlockwood** [comment]
@moallemi this still doesn't work:

```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all artifacts for configuration ':app:classpath'.
   > Could not find com.android.tools.build:gradle:7.0.0-beta03.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/android/tools/build/gradle/7.0.0-beta03/gradle-7.0.0-beta03.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :app > me.moallemi.gradle:advanced-build-version:1.7.4
```

**Comment by murdak** [comment]
AGP 7.1.2
Gradle 7.2

An exception occurred applying plugin request [id: 'me.moallemi.advanced-build-version', version: '2.0.0']
> Failed to apply plugin 'me.moallemi.advanced-build-version'.
   > The Android Gradle plugin not found. gradle-advanced-build-version only works with Android gradle library.

**Comment by moallemi** [comment]
@murdak Based on error message it seems that you are applying this plugin on a Non-Android repository. make sure that you follow the docs for setting up the library

**Comment by murdak** [comment]
> 

Can you elaborate? Do you have a sample app project?
I'm using latest android studio (bumblebee). Created a project with basic activity, and then follow README instructions for installation and usage of plugin. After syncing I get the error I posted.

Here is from build.gradle

plugins {
    id 'com.android.application' version '7.1.1' apply false
    id 'com.android.library' version '7.1.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.6.10' apply false

    id "me.moallemi.advanced-build-version" version "2.0.0"
}

**Comment by moallemi** [comment]
@murdak Thank you for raising this issue. I have to update the plugin to support the new project setup. but for now you can follow these steps:

### in `root`  **build.gradle**

![CleanShot 2022-04-09 at 11 15 47@2x](https://user-images.githubusercontent.com/1250691/162565422-56740a62-d940-45f9-b6ab-0453132b90b7.png)

### in `app` **build.gradle**

![CleanShot 2022-04-09 at 11 16 11@2x](https://user-images.githubusercontent.com/1250691/162565437-3694c329-e85c-4fc0-82ad-97cb8f3f0afb.png)
