### ISSUE TITLE
No AGP 8.0 support

### ISSUE THREAD

**Issue by mieszk3** [moallemi/gradle-advanced-build-version#67]
After update AGP to 8.0 (stable) `gradle-advanced-build-version` throws an exception `gradle-advanced-build-version does not support Android Gradle plugin 8.0.0`

**Comment by gn1024** [comment]
Same here. Could you make the required changes, please?

**Comment by moallemi** [comment]
Working on it, stay tuned

**Comment by moallemi** [comment]
@mieszk3 @gn1024 please try v**2.0.2** and let me know if it works for you

**Comment by mieszk3** [comment]
@moallemi Yes, it works!

**Comment by gn1024** [comment]
> @mieszk3 @gn1024 please try v**2.0.2** and let me know if it works for you

Thank you! It works :)

**Comment by pdecat** [comment]
FWIW, v2.0.2 was not published as a Github release, made my think v2.0.1 was the most recent version:

![image](https://github.com/moallemi/gradle-advanced-build-version/assets/318490/50f3749a-aa01-44bb-ad75-0a921787f582)
